# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Posts"
  url = "post/"
  weight = 1

[[main]]
    name = "Courses"
    url = "courses/"
    weight=3

[[main]]
    name = "Books"
    url = "books/"
    weight=3

[[main]]
    name = "All Courses"
    url = "courses/"
    parent = "Courses"
    weight=1

[[main]]
    name = "Operating system"
    url = "courses/operating_system"
    parent = "Courses"
    weight=3

[[main]]
    name = "Computer network"
    url = "courses/computer_network"
    parent = "Courses"
    weight=4

[[main]]
    name = "Deep Learning"
    url = "courses/deep_learning"
    parent = "Courses"
    weight=2


[[main]]
  name = "Home"
  url = "#about"
  identifier = "home"
  weight = 10


# [[main]]
#     name = "Tags"
#     url = "tag/"
#     weight=5

# [[main]]
  # parent = "home"
  # name = "Projects"
  # url = "#projects"
  # weight = 30


# [[main]]
  # parent = "home"
  # name = "Publications"
  # url = "#featured"
  # weight = 40


# [[main]]
  # parent = "home"
  # name = "Contact"
  # url = "#contact"
  # weight = 60


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
